---
# tasks file for db
- name: 'Add mongodb repo 4.0'
  yum_repository:
    name: "mongodb"
    description: "MongoDB Repository"
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    gpgcheck: no
    enabled: yes
    file: mongodb
  

- name: 'Install mongodb-org'
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mongo-10gen
    - mongo-10gen-server

