---
# tasks file for db
- name: 'Add mongodb repo 4.0'
  yum_repository:
    name: "mongodb"
    description: "MongoDB Repository"
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    gpgcheck: no
    enabled: yes
    file: mongodb
  

- name: 'Install mongodb-org'
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mongo-10gen
    - mongo-10gen-server


# NOTE: Before 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
- name: Allow remote login
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^bind_ip=127.0.0.1'
    line: bind_ip=0.0.0.0
  notify:
    - restart mongodb

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  systemd:
    name: mongod
    enabled: yes
    state: started

