---
# tasks file for docker
  - name: update system
    shell: yum update -y

  - name: add docker-ce-stable repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: update system
    shell: yum install -y docker-ce --nobest
  
  - name: allow jenkins to run docker commands
    shell: usermod -aG docker jenkins

  - name: Ensure docker is running and and enabled to start automatically on reboots
    systemd:
      name: docker
      enabled: yes
      state: started
