- hosts: staging
  tasks:
    - name: set DATABASE_URL
      shell: "export DATABASE_URL=$URL"
      environment:
        URL: mongodb://10.10.11.117/yelp_camp_5
    
    - name: pull image 
      vars:
         build_number: {{ build_number}}
      shell: docker pull manrodri/yelpcamp:{{ build_number }}
    
    - name: run container on port 3000
      shell: docker run  --name yelpCamp -p 3000:3000  -d manrodri/yelpcamp:latest