- hosts: staging
  tasks:
    - name: set DATABASE_URL
      shell: "export DATABASE_URL=mongodb://10.10.11.117/yelp_camp_5 >> /etc/profile.d/mongo.sh && chmod 755 /etc/profile.d/mongo.sh"
      become: yes
    
    - name: pull image 
      shell: docker pull manrodri/yelpcamp:{{ build_number }}
    
    - name: run container on port 3000
      shell: docker run  --name yelpCamp -p 3000:3000  -d manrodri/yelpcamp:{{ build_number }}