- hosts: staging
  tasks:
    - name: pull image 
      shell: docker pull manrodri/yelpcamp:{{ build_number }}
    
    - name: stop container
      shell: docker stop yelpCamp
    
    - name: remove container
      shell: docker rm yelpCamp
    
    - name: run container on port 80 with restart always policy
      shell: docker run  --name yelpCamp -p 80:3000  --restart=always -d manrodri/yelpcamp:{{ build_number }}

    