- hosts: staging
  tasks:
    - name: set DATABASE_URL
      shell: "export DATABASE_URL=$URL"
      environment:
        URL: mongodb://10.10.11.117/yelp_camp_5

    - name: pull image 
      shell: docker pull manrodri/yelpcamp:latest
    
    - name: stop container
      shell: docker stop yelpCamp
    
    - name: remove container
      shell: docker rm yelpCamp
    
    - name: run container on port 80 with restart always policy
      shell: docker run  --name yelpCamp -p 3000:3000  -d manrodri/yelpcamp:latest

    